title   Jarvis-OS
linux   /jarvis/vmlinuz-linux
initrd  /jarvis/initramfs-linux.img
options archisobasedir=jarvis archisolabel=JARVIS_LABEL quiet splash loglevel=0 vt.global_cursor_default=0 vt.default_utf8=0 logo.nologo
