logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth()/2 - logo.image.GetWidth()/2);
logo.sprite.SetY(Window.GetHeight()/2 - logo.image.GetHeight()/2 - 40);

fun boot_progress_cb(duration, progress) {
  bar_width = Window.GetWidth() * 0.4 * progress;
  progress_bar.sprite.SetImage(progress_bar.image.Scale(bar_width, progress_bar.image.GetHeight()));
}
Plymouth.SetBootProgressFunction(boot_progress_cb);
